import { MapType } from './map.types';

export const initialMap: MapType = {
    0: [
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
    ],
    1: [
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
    ],
    2: [
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
    ],
    3: [
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'path' },
    ],
    4: [
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
    ],
    5: [
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'path' },
    ],
    6: [
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
    ],
    7: [
      { style: 'path' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'wall' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'path' },
      { style: 'wall' },
      { style: 'path' },
    ],
  };